version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.${ENVIRONMENT}
    environment:
      - ENVIRONMENT=${ENVIRONMENT}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.${ENVIRONMENT}
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
